services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dlu
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
