services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dlu
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    build:
      context: .
      dockerfile_inline: |
        FROM dpage/pgadmin4
        COPY servers.json /pgadmin4/servers.json
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "dlu@student.42belrin.de"
      PGADMIN_DEFAULT_PASSWORD: "mysecretpassword"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
